pub mod clock;
pub mod containers;
pub mod desktop;
pub mod editor;
pub mod emulator;
pub mod filesystem;
pub mod persistence;
pub mod platform;
pub mod process;
pub mod terminal;

pub use clock::Clock;
pub use containers::ContainerBackend;
pub use desktop::{DesktopBackend, DesktopSnapshot};
pub use editor::EditorBackend;
pub use emulator::EmulatorBackend;
pub use filesystem::FileSystem;
pub use persistence::{ConfigStore, StateStore};
pub use platform::PlatformDetector;
pub use process::{BoxFuture, ProcessOutput, ProcessRequest, ProcessRunner};
pub use terminal::TerminalBackend;
